# Generated by Django 5.1.1 on 2024-12-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0004_customuser_cod_customuser_email_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
