# Generated by Django 5.1.1 on 2025-01-04 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0005_alter_customuser_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclefleet',
            name='manufacture_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
