# Generated by Django 5.1.1 on 2025-01-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0006_alter_vehiclefleet_manufacture_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': [('view_offer', 'Can view special offer')]},
        ),
    ]
