# Generated by Django 5.1.1 on 2025-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0008_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
