# Generated by Django 5.1.1 on 2025-01-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0009_customuser_blocat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user', 'Can change user'), ('view_user', 'Can view user')]},
        ),
    ]
