# Generated by Django 5.1.1 on 2025-01-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user', 'Can change user'), ('view_user', 'Can view user'), ('change_blocat', 'Can block/unblock users')]},
        ),
    ]
