# Generated by Django 5.1.1 on 2025-01-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brutarie', '0011_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_user', 'Can view user'), ('change_first_name', 'Can change first name'), ('change_last_name', 'Can change last name'), ('change_email', 'Can change email'), ('change_blocat', 'Can block/unblock users')]},
        ),
    ]
